package kalkulator_matriks;


import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;
/**
 *
 * @author digit
 */
public class Aritmatika extends javax.swing.JFrame {

    /**
     * Creates new form Aritmatika
     */
    public Aritmatika() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Operasi1 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jPanel24 = new javax.swing.JPanel();
        A3 = new javax.swing.JTextField();
        A1 = new javax.swing.JTextField();
        A2 = new javax.swing.JTextField();
        A4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel25 = new javax.swing.JPanel();
        H4 = new javax.swing.JTextField();
        H2 = new javax.swing.JTextField();
        H3 = new javax.swing.JTextField();
        H1 = new javax.swing.JTextField();
        jPanel26 = new javax.swing.JPanel();
        B4 = new javax.swing.JTextField();
        B2 = new javax.swing.JTextField();
        B3 = new javax.swing.JTextField();
        B1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Reset2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jA1 = new javax.swing.JTextField();
        jA2 = new javax.swing.JTextField();
        jA3 = new javax.swing.JTextField();
        jA6 = new javax.swing.JTextField();
        jA5 = new javax.swing.JTextField();
        jA4 = new javax.swing.JTextField();
        jA7 = new javax.swing.JTextField();
        jA8 = new javax.swing.JTextField();
        jA9 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jB1 = new javax.swing.JTextField();
        jB2 = new javax.swing.JTextField();
        jB3 = new javax.swing.JTextField();
        jB6 = new javax.swing.JTextField();
        jB5 = new javax.swing.JTextField();
        jB4 = new javax.swing.JTextField();
        jB7 = new javax.swing.JTextField();
        jB8 = new javax.swing.JTextField();
        jB9 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jH1 = new javax.swing.JTextField();
        jH2 = new javax.swing.JTextField();
        jH3 = new javax.swing.JTextField();
        jH6 = new javax.swing.JTextField();
        jH5 = new javax.swing.JTextField();
        jH4 = new javax.swing.JTextField();
        jH7 = new javax.swing.JTextField();
        jH8 = new javax.swing.JTextField();
        jH9 = new javax.swing.JTextField();
        Operasi2 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Reset3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        A21 = new javax.swing.JTextField();
        A11 = new javax.swing.JTextField();
        A12 = new javax.swing.JTextField();
        A22 = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        B22 = new javax.swing.JTextField();
        B12 = new javax.swing.JTextField();
        B21 = new javax.swing.JTextField();
        B11 = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        C31 = new javax.swing.JTextField();
        C21 = new javax.swing.JTextField();
        C22 = new javax.swing.JTextField();
        C32 = new javax.swing.JTextField();
        C12 = new javax.swing.JTextField();
        C11 = new javax.swing.JTextField();
        ResetTask = new javax.swing.JButton();
        HitungTask = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        S1b = new javax.swing.JTextField();
        S1a = new javax.swing.JTextField();
        S1d = new javax.swing.JTextField();
        S1c = new javax.swing.JTextField();
        S1f = new javax.swing.JTextField();
        S1e = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        S2a = new javax.swing.JTextField();
        S2b = new javax.swing.JTextField();
        S2c = new javax.swing.JTextField();
        S2d = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        S3a = new javax.swing.JTextField();
        S3b = new javax.swing.JTextField();
        S3e = new javax.swing.JTextField();
        S3d = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        S3c = new javax.swing.JTextField();
        S3f = new javax.swing.JTextField();
        jSeparator20 = new javax.swing.JSeparator();
        S4a = new javax.swing.JTextField();
        S4b = new javax.swing.JTextField();
        S4d = new javax.swing.JTextField();
        S4c = new javax.swing.JTextField();
        jSeparator21 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Operasi Aritmatika");

        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("OPERASI ARITMATIKA");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(330, 20, 147, 20);

        Operasi1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OPERASI", "Penjumlahan", "Pengurangan", "Perkalian" }));
        Operasi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Operasi1ActionPerformed(evt);
            }
        });
        jPanel3.add(Operasi1);
        Operasi1.setBounds(231, 273, 140, 22);

        jButton3.setBackground(new java.awt.Color(153, 204, 255));
        jButton3.setText("Kembali");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(40, 420, 100, 22);

        jPanel24.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Matriks A"));
        jPanel24.setName(""); // NOI18N
        jPanel24.setPreferredSize(new java.awt.Dimension(130, 100));
        jPanel24.setLayout(null);

        A3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel24.add(A3);
        A3.setBounds(11, 60, 50, 30);

        A1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel24.add(A1);
        A1.setBounds(11, 24, 50, 30);

        A2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel24.add(A2);
        A2.setBounds(73, 24, 50, 30);

        A4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel24.add(A4);
        A4.setBounds(73, 60, 50, 30);

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setText("Tranpose");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel24.add(jButton2);
        jButton2.setBounds(10, 100, 120, 22);

        jPanel3.add(jPanel24);
        jPanel24.setBounds(229, 130, 140, 130);

        jPanel25.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hasil", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel25.setName(""); // NOI18N
        jPanel25.setLayout(null);

        H4.setEditable(false);
        H4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel25.add(H4);
        H4.setBounds(73, 60, 50, 30);

        H2.setEditable(false);
        H2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel25.add(H2);
        H2.setBounds(73, 24, 50, 30);

        H3.setEditable(false);
        H3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel25.add(H3);
        H3.setBounds(11, 60, 50, 30);

        H1.setEditable(false);
        H1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel25.add(H1);
        H1.setBounds(11, 24, 50, 30);

        jPanel3.add(jPanel25);
        jPanel25.setBounds(440, 270, 140, 100);

        jPanel26.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Matriks B"));
        jPanel26.setName(""); // NOI18N
        jPanel26.setLayout(null);

        B4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel26.add(B4);
        B4.setBounds(73, 60, 50, 30);

        B2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel26.add(B2);
        B2.setBounds(73, 24, 50, 30);

        B3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel26.add(B3);
        B3.setBounds(11, 60, 50, 30);

        B1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel26.add(B1);
        B1.setBounds(11, 24, 50, 30);

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setText("Tranpose");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel26.add(jButton1);
        jButton1.setBounds(10, 100, 120, 22);

        jPanel3.add(jPanel26);
        jPanel26.setBounds(440, 130, 140, 130);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel10.setText("Ordo 2 x 2");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(370, 60, 60, 16);

        Reset2.setBackground(new java.awt.Color(255, 0, 0));
        Reset2.setForeground(new java.awt.Color(255, 255, 255));
        Reset2.setText("Reset");
        Reset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset2ActionPerformed(evt);
            }
        });
        jPanel3.add(Reset2);
        Reset2.setBounds(150, 420, 100, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Lorenza\\Matkul sem 3\\Aljabar Linear dan Matriks\\Tugas\\20230114_175711_0000.png")); // NOI18N
        jPanel3.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 470);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("2 x 2", jPanel1);

        jPanel2.setLayout(null);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Matriks A"));
        jPanel7.setLayout(null);

        jA1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(jA1);
        jA1.setBounds(25, 24, 50, 30);

        jA2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(jA2);
        jA2.setBounds(93, 24, 50, 30);

        jA3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(jA3);
        jA3.setBounds(161, 24, 50, 30);

        jA6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(jA6);
        jA6.setBounds(161, 66, 50, 30);

        jA5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(jA5);
        jA5.setBounds(93, 66, 50, 30);

        jA4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(jA4);
        jA4.setBounds(25, 66, 50, 30);

        jA7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(jA7);
        jA7.setBounds(25, 108, 50, 30);

        jA8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(jA8);
        jA8.setBounds(93, 108, 50, 30);

        jA9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(jA9);
        jA9.setBounds(161, 108, 50, 30);

        jButton7.setBackground(new java.awt.Color(204, 204, 255));
        jButton7.setText("Tranpose");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton7);
        jButton7.setBounds(20, 150, 200, 22);

        jPanel2.add(jPanel7);
        jPanel7.setBounds(125, 95, 240, 180);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Matriks B"));
        jPanel8.setLayout(null);

        jB1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel8.add(jB1);
        jB1.setBounds(25, 24, 50, 30);

        jB2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel8.add(jB2);
        jB2.setBounds(93, 24, 50, 30);

        jB3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel8.add(jB3);
        jB3.setBounds(161, 24, 50, 30);

        jB6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel8.add(jB6);
        jB6.setBounds(161, 66, 50, 30);

        jB5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel8.add(jB5);
        jB5.setBounds(93, 66, 50, 30);

        jB4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel8.add(jB4);
        jB4.setBounds(25, 66, 50, 30);

        jB7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel8.add(jB7);
        jB7.setBounds(25, 108, 50, 30);

        jB8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel8.add(jB8);
        jB8.setBounds(93, 108, 50, 30);

        jB9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel8.add(jB9);
        jB9.setBounds(161, 108, 50, 30);

        jButton6.setBackground(new java.awt.Color(204, 204, 255));
        jButton6.setText("Tranpose");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton6);
        jButton6.setBounds(20, 150, 200, 22);

        jPanel2.add(jPanel8);
        jPanel8.setBounds(438, 95, 240, 180);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hasil", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel9.setLayout(null);

        jH1.setEditable(false);
        jH1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel9.add(jH1);
        jH1.setBounds(25, 28, 50, 30);

        jH2.setEditable(false);
        jH2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel9.add(jH2);
        jH2.setBounds(93, 28, 50, 30);

        jH3.setEditable(false);
        jH3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel9.add(jH3);
        jH3.setBounds(161, 28, 50, 30);

        jH6.setEditable(false);
        jH6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel9.add(jH6);
        jH6.setBounds(161, 70, 50, 30);

        jH5.setEditable(false);
        jH5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel9.add(jH5);
        jH5.setBounds(93, 70, 50, 30);

        jH4.setEditable(false);
        jH4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel9.add(jH4);
        jH4.setBounds(25, 70, 50, 30);

        jH7.setEditable(false);
        jH7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel9.add(jH7);
        jH7.setBounds(25, 112, 50, 30);

        jH8.setEditable(false);
        jH8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel9.add(jH8);
        jH8.setBounds(93, 112, 50, 30);

        jH9.setEditable(false);
        jH9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel9.add(jH9);
        jH9.setBounds(161, 112, 50, 30);

        jPanel2.add(jPanel9);
        jPanel9.setBounds(440, 290, 240, 160);

        Operasi2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OPERASI", "Penjumlahan", "Pengurangan", "Perkalian" }));
        Operasi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Operasi2ActionPerformed(evt);
            }
        });
        jPanel2.add(Operasi2);
        Operasi2.setBounds(130, 290, 236, 22);

        jButton4.setBackground(new java.awt.Color(153, 204, 255));
        jButton4.setText("Kembali");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(40, 420, 100, 22);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel13.setText("Ordo 3 x 3");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(370, 60, 60, 16);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("OPERASI ARITMATIKA");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(330, 20, 147, 20);

        Reset3.setBackground(new java.awt.Color(255, 0, 0));
        Reset3.setForeground(new java.awt.Color(255, 255, 255));
        Reset3.setText("Reset");
        Reset3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset3ActionPerformed(evt);
            }
        });
        jPanel2.add(Reset3);
        Reset3.setBounds(150, 420, 100, 22);

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Lorenza\\Matkul sem 3\\Aljabar Linear dan Matriks\\Tugas\\20230114_175711_0000.png")); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 0, 800, 470);

        jTabbedPane1.addTab("3 x 3", jPanel2);

        jPanel10.setLayout(null);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Matriks A"));
        jPanel11.setName(""); // NOI18N
        jPanel11.setLayout(null);

        A21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel11.add(A21);
        A21.setBounds(11, 60, 50, 30);

        A11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel11.add(A11);
        A11.setBounds(11, 24, 50, 30);

        A12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel11.add(A12);
        A12.setBounds(73, 24, 50, 30);

        A22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel11.add(A22);
        A22.setBounds(73, 60, 50, 30);

        jPanel10.add(jPanel11);
        jPanel11.setBounds(90, 110, 140, 100);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Matriks B"));
        jPanel12.setName(""); // NOI18N
        jPanel12.setLayout(null);

        B22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel12.add(B22);
        B22.setBounds(73, 60, 50, 30);

        B12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel12.add(B12);
        B12.setBounds(73, 24, 50, 30);

        B21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel12.add(B21);
        B21.setBounds(11, 60, 50, 30);

        B11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel12.add(B11);
        B11.setBounds(11, 24, 50, 30);

        jPanel10.add(jPanel12);
        jPanel12.setBounds(250, 110, 140, 100);

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Matriks C"));
        jPanel13.setName(""); // NOI18N
        jPanel13.setLayout(null);

        C31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel13.add(C31);
        C31.setBounds(11, 96, 50, 30);

        C21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel13.add(C21);
        C21.setBounds(11, 60, 50, 30);

        C22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel13.add(C22);
        C22.setBounds(73, 60, 50, 30);

        C32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel13.add(C32);
        C32.setBounds(73, 96, 50, 30);

        C12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel13.add(C12);
        C12.setBounds(73, 24, 50, 30);

        C11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel13.add(C11);
        C11.setBounds(11, 24, 50, 30);

        jPanel10.add(jPanel13);
        jPanel13.setBounds(90, 230, 140, 140);

        ResetTask.setBackground(new java.awt.Color(255, 0, 0));
        ResetTask.setForeground(new java.awt.Color(255, 255, 255));
        ResetTask.setText("RESET");
        ResetTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetTaskActionPerformed(evt);
            }
        });
        jPanel10.add(ResetTask);
        ResetTask.setBounds(250, 330, 140, 22);

        HitungTask.setBackground(new java.awt.Color(204, 204, 204));
        HitungTask.setText("HITUNG");
        HitungTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungTaskActionPerformed(evt);
            }
        });
        jPanel10.add(HitungTask);
        HitungTask.setBounds(250, 260, 140, 50);

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "HASIL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel14.setLayout(null);

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel14.add(jSeparator4);
        jSeparator4.setBounds(131, 144, 3, 66);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel16.setText("A");
        jPanel14.add(jLabel16);
        jLabel16.setBounds(55, 167, 8, 16);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabel17.setText("t");
        jPanel14.add(jLabel17);
        jLabel17.setBounds(69, 159, 8, 14);

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel14.add(jSeparator5);
        jSeparator5.setBounds(247, 144, 3, 66);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabel18.setText("t");
        jPanel14.add(jLabel18);
        jLabel18.setBounds(411, 57, 3, 14);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel19.setText("(CB)");
        jPanel14.add(jLabel19);
        jLabel19.setBounds(382, 65, 23, 16);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel20.setText("=");
        jPanel14.add(jLabel20);
        jLabel20.setBounds(420, 65, 8, 16);

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel14.add(jSeparator7);
        jSeparator7.setBounds(440, 42, 3, 66);

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel14.add(jSeparator8);
        jSeparator8.setBounds(607, 42, 3, 66);

        jLabel27.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabel27.setText("t");
        jPanel14.add(jLabel27);
        jLabel27.setBounds(380, 148, 3, 14);

        jLabel28.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel28.setText("(A");
        jPanel14.add(jLabel28);
        jLabel28.setBounds(362, 156, 12, 16);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel29.setText("x B) - (B x A");
        jPanel14.add(jLabel29);
        jLabel29.setBounds(389, 156, 60, 16);

        jLabel30.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabel30.setText("t");
        jPanel14.add(jLabel30);
        jLabel30.setBounds(455, 148, 3, 14);

        jLabel31.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel31.setText(") =");
        jPanel14.add(jLabel31);
        jLabel31.setBounds(464, 156, 15, 16);

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel14.add(jSeparator9);
        jSeparator9.setBounds(491, 130, 3, 66);

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel14.add(jSeparator10);
        jSeparator10.setBounds(607, 130, 3, 66);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel6.setText("CA =");
        jPanel14.add(jLabel6);
        jLabel6.setBounds(98, 66, 27, 16);

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel14.add(jSeparator2);
        jSeparator2.setBounds(131, 24, 3, 102);

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel14.add(jSeparator3);
        jSeparator3.setBounds(247, 24, 3, 102);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel11.setText("(A+B) =");
        jPanel14.add(jLabel11);
        jLabel11.setBounds(83, 167, 42, 16);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel15);
        jPanel15.setBounds(140, 30, 0, 90);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel16);
        jPanel16.setBounds(140, 150, 0, 60);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel17);
        jPanel17.setBounds(500, 130, 0, 60);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel18);
        jPanel18.setBounds(450, 40, 150, 70);

        jPanel10.add(jPanel14);
        jPanel14.setBounds(50, 196, 0, 0);

        jButton5.setBackground(new java.awt.Color(153, 204, 255));
        jButton5.setText("Kembali");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton5);
        jButton5.setBounds(40, 420, 100, 22);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\Lorenza\\Matkul sem 3\\Aljabar Linear dan Matriks\\Tugas\\icon 2.png")); // NOI18N
        jPanel10.add(jLabel8);
        jLabel8.setBounds(170, 10, 60, 70);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel9.setText("Task");
        jPanel10.add(jLabel9);
        jLabel9.setBounds(240, 30, 50, 25);

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "HASIL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel21.setText("A");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabel22.setText("t");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabel23.setText("t");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel24.setText("(CB)");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel25.setText("=");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabel32.setText("t");

        jLabel33.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel33.setText("(B");

        jLabel34.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel34.setText("x A) - (A ");

        jLabel35.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabel35.setText("t");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel36.setText("x B) =");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel7.setText("CA =");

        jSeparator16.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator16.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel12.setText("(A+B) =");

        S1b.setEditable(false);
        S1b.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        S1a.setEditable(false);
        S1a.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        S1d.setEditable(false);
        S1d.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        S1c.setEditable(false);
        S1c.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        S1f.setEditable(false);
        S1f.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        S1e.setEditable(false);
        S1e.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jSeparator18.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator18.setOrientation(javax.swing.SwingConstants.VERTICAL);

        S2a.setEditable(false);
        S2a.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        S2b.setEditable(false);
        S2b.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        S2c.setEditable(false);
        S2c.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        S2d.setEditable(false);
        S2d.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jSeparator17.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator17.setOrientation(javax.swing.SwingConstants.VERTICAL);

        S3a.setEditable(false);
        S3a.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        S3b.setEditable(false);
        S3b.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        S3e.setEditable(false);
        S3e.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        S3d.setEditable(false);
        S3d.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jSeparator19.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator19.setOrientation(javax.swing.SwingConstants.VERTICAL);

        S3c.setEditable(false);
        S3c.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        S3f.setEditable(false);
        S3f.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jSeparator20.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator20.setOrientation(javax.swing.SwingConstants.VERTICAL);

        S4a.setEditable(false);
        S4a.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        S4b.setEditable(false);
        S4b.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        S4d.setEditable(false);
        S4d.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        S4c.setEditable(false);
        S4c.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jSeparator21.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator21.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(S1a, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(S1c, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(S1e, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(S1b, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(S1d, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(S1f, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel21)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel12)
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(S2a, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(S2c, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(S2b, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(S2d, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel33)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel32)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel34)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(S4a, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(S4c, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(S4b, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(S4d, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator21, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel24)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel23)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(S3a, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(S3d, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(S3b, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(S3e, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(S3c, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(S3f, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel7))
                    .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(S1a, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(S1c, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(S1e, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(S1b, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(S1d, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(S1f, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addGroup(jPanel19Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel12)))))
                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(S2a, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(S2c, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(S2b, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(S2d, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel19Layout.createSequentialGroup()
                            .addComponent(S3a, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(S3d, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel19Layout.createSequentialGroup()
                            .addComponent(S3b, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(S3e, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel19Layout.createSequentialGroup()
                            .addComponent(S3c, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(S3f, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addGroup(jPanel19Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25))))
                        .addGap(25, 25, 25)))
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel35)
                            .addGroup(jPanel19Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel36)))))
                    .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(S4a, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(S4c, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(S4b, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(S4d, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator21, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel10.add(jPanel19);
        jPanel19.setBounds(430, 20, 350, 430);

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\Lorenza\\Matkul sem 3\\Aljabar Linear dan Matriks\\Tugas\\20230114_175711_0000.png")); // NOI18N
        jPanel10.add(jLabel5);
        jLabel5.setBounds(0, 0, 800, 470);

        jTabbedPane1.addTab("Task", jPanel10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void Reset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset2ActionPerformed
        A1.setText("");
        A2.setText("");
        A3.setText("");
        A4.setText("");
        B1.setText("");
        B2.setText("");
        B3.setText("");
        B4.setText("");
        H1.setText("");
        H2.setText("");
        H3.setText("");
        H4.setText("");
    }//GEN-LAST:event_Reset2ActionPerformed

    private void Reset3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset3ActionPerformed
        jA1.setText("");
        jA2.setText("");
        jA3.setText("");
        jA4.setText("");
        jA5.setText("");
        jA6.setText("");
        jA7.setText("");
        jA8.setText("");
        jA9.setText("");
        jB1.setText("");
        jB2.setText("");
        jB3.setText("");
        jB4.setText("");
        jB5.setText("");
        jB6.setText("");
        jB7.setText("");
        jB8.setText("");
        jB9.setText("");
        jH1.setText("");
        jH2.setText("");
        jH3.setText("");
        jH4.setText("");
        jH5.setText("");
        jH6.setText("");
        jH7.setText("");
        jH8.setText("");
        jH9.setText("");
    }//GEN-LAST:event_Reset3ActionPerformed

    private void ResetTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetTaskActionPerformed
        A11.setText("");
        A12.setText("");
        A21.setText("");
        A22.setText("");
        B11.setText("");
        B12.setText("");
        B21.setText("");
        B22.setText("");
        C11.setText("");
        C12.setText("");
        C21.setText("");
        C22.setText("");
        C31.setText("");
        C32.setText("");
        S1a.setText("");
        S1b.setText("");
        S1c.setText("");
        S1d.setText("");
        S1e.setText("");
        S1f.setText("");
        S2a.setText("");
        S2b.setText("");
        S2c.setText("");
        S2d.setText("");
        S3a.setText("");
        S3b.setText("");
        S3c.setText("");
        S3d.setText("");
        S3e.setText("");
        S3f.setText("");
        S4a.setText("");
        S4b.setText("");
        S4c.setText("");
        S4d.setText("");
    }//GEN-LAST:event_ResetTaskActionPerformed

    private void Operasi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Operasi1ActionPerformed
        int matriksA[][] = new int[2][2];
        int matriksB[][] = new int[2][2];
        int matriksC[][] = new int[2][2];
        
        try{
            matriksA[0][0] = Integer.parseInt(A1.getText());
            matriksA[0][1] = Integer.parseInt(A2.getText());
            matriksA[1][0] = Integer.parseInt(A3.getText());
            matriksA[1][1] = Integer.parseInt(A4.getText());

            matriksB[0][0] = Integer.parseInt(B1.getText());
            matriksB[0][1] = Integer.parseInt(B2.getText());
            matriksB[1][0] = Integer.parseInt(B3.getText());
            matriksB[1][1] = Integer.parseInt(B4.getText());
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Yang anda masukkan salah atau kosong");
        }
        
        Object pilih = Operasi1.getSelectedItem();
        if(pilih.equals("OPERASI")){
            H1.setText("");
            H2.setText("");
            H3.setText("");
            H4.setText("");
        }else if(pilih.equals("Penjumlahan")){
            for(int i=0; i<matriksA.length; i++){
                for(int j=0; j<matriksA[0].length; j++){
                    matriksC[i][j] = matriksA[i][j] + matriksB[i][j];
                }
            }
        } else if(pilih.equals("Pengurangan")){
            for(int i=0; i<matriksA.length; i++){
                for(int j=0; j<matriksA[0].length; j++){
                    matriksC[i][j] = matriksA[i][j] - matriksB[i][j];
                }
            }
        } else if(pilih.equals("Perkalian")){
            for(int i=0; i<matriksA.length; i++){
                for(int j=0; j<matriksA[0].length; j++){
                    int hasil = 0;
                    for(int k=0; k<matriksA.length; k++){
                        hasil += matriksA[i][k] * matriksB[k][j];
                    }
                    matriksC[i][j] = hasil;
                }
            }
        }
        H1.setText(String.valueOf(matriksC[0][0]));
        H2.setText(String.valueOf(matriksC[0][1]));
        H3.setText(String.valueOf(matriksC[1][0]));
        H4.setText(String.valueOf(matriksC[1][1]));
    }//GEN-LAST:event_Operasi1ActionPerformed

    private void Operasi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Operasi2ActionPerformed
        int matriksA[][] = new int[3][3];
        int matriksB[][] = new int[3][3];
        int matriksC[][] = new int[3][3];
        
        try{
            matriksA[0][0] = Integer.parseInt(jA1.getText());
            matriksA[0][1] = Integer.parseInt(jA2.getText());
            matriksA[0][2] = Integer.parseInt(jA3.getText());
            matriksA[1][0] = Integer.parseInt(jA4.getText());
            matriksA[1][1] = Integer.parseInt(jA5.getText());
            matriksA[1][2] = Integer.parseInt(jA6.getText());
            matriksA[2][0] = Integer.parseInt(jA7.getText());
            matriksA[2][1] = Integer.parseInt(jA8.getText());
            matriksA[2][2] = Integer.parseInt(jA9.getText());

            matriksB[0][0] = Integer.parseInt(jB1.getText());
            matriksB[0][1] = Integer.parseInt(jB2.getText());
            matriksB[0][2] = Integer.parseInt(jB3.getText());
            matriksB[1][0] = Integer.parseInt(jB4.getText());
            matriksB[1][1] = Integer.parseInt(jB5.getText());
            matriksB[1][2] = Integer.parseInt(jB6.getText());
            matriksB[2][0] = Integer.parseInt(jB7.getText());
            matriksB[2][1] = Integer.parseInt(jB8.getText());
            matriksB[2][2] = Integer.parseInt(jB9.getText());
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Yang anda masukkan salah atau kosong");
        }
            
        Object pilih1 = Operasi2.getSelectedItem();
        if(pilih1.equals("OPERASI")){
            jH1.setText("");
            jH2.setText("");
            jH3.setText("");
            jH4.setText("");
            jH5.setText("");
            jH6.setText("");
            jH7.setText("");
            jH8.setText("");
            jH9.setText("");
        }else if(pilih1.equals("Penjumlahan")){
            for(int i=0; i<matriksA.length; i++){
                for(int j=0; j<matriksA[0].length; j++){
                    matriksC[i][j] = matriksA[i][j] + matriksB[i][j];
                }
            }
        } else if(pilih1.equals("Pengurangan")){
            for(int i=0; i<matriksA.length; i++){
                for(int j=0; j<matriksA[0].length; j++){
                    matriksC[i][j] = matriksA[i][j] - matriksB[i][j];
                }
            }
        } else if(pilih1.equals("Perkalian")){
            for(int i=0; i<matriksA.length; i++){
                for(int j=0; j<matriksA[0].length; j++){
                    int hasil = 0;
                    for(int k=0; k<matriksA.length; k++){
                        hasil += matriksA[i][k] * matriksB[k][j];
                    }
                    matriksC[i][j] = hasil;
                }
            }
        }
        jH1.setText(String.valueOf(matriksC[0][0]));
        jH2.setText(String.valueOf(matriksC[0][1]));
        jH3.setText(String.valueOf(matriksC[0][2]));
        jH4.setText(String.valueOf(matriksC[1][0]));
        jH5.setText(String.valueOf(matriksC[1][1]));
        jH6.setText(String.valueOf(matriksC[1][2]));
        jH7.setText(String.valueOf(matriksC[2][0]));
        jH8.setText(String.valueOf(matriksC[2][1]));
        jH9.setText(String.valueOf(matriksC[2][2]));
    }//GEN-LAST:event_Operasi2ActionPerformed

    private void HitungTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungTaskActionPerformed
        int matriksA[][] = new int[2][2];
        int matriksB[][] = new int[2][2];
        int matriksC[][] = new int[3][2];
        
        try{
            matriksA[0][0] = Integer.parseInt(A11.getText());
            matriksA[0][1] = Integer.parseInt(A12.getText());
            matriksA[1][0] = Integer.parseInt(A21.getText());
            matriksA[1][1] = Integer.parseInt(A22.getText());

            matriksB[0][0] = Integer.parseInt(B11.getText());
            matriksB[0][1] = Integer.parseInt(B12.getText());
            matriksB[1][0] = Integer.parseInt(B21.getText());
            matriksB[1][1] = Integer.parseInt(B22.getText());

            matriksC[0][0] = Integer.parseInt(C11.getText());
            matriksC[0][1] = Integer.parseInt(C12.getText());
            matriksC[1][0] = Integer.parseInt(C21.getText());
            matriksC[1][1] = Integer.parseInt(C22.getText());
            matriksC[2][0] = Integer.parseInt(C31.getText());
            matriksC[2][1] = Integer.parseInt(C32.getText());
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Yang anda masukkan salah atau kosong");
        }
        
        // A tranpose
        int Atr[][] = new int[2][2];
        Atr[0][0] = matriksA[0][0];
        Atr[0][1] = matriksA[1][0];
        Atr[1][0] = matriksA[0][1];
        Atr[1][1] = matriksA[1][1];
        
        // Soal A
        int matriks1[][] = new int[3][2];
        matriks1[0][0] = matriksC[0][0]*matriksA[0][0] + matriksC[0][1]*matriksA[1][0];
        matriks1[0][1] = matriksC[0][0]*matriksA[0][1] + matriksC[0][1]*matriksA[1][1];
        matriks1[1][0] = matriksC[1][0]*matriksA[0][0] + matriksC[1][1]*matriksA[1][0];
        matriks1[1][1] = matriksC[1][0]*matriksA[0][1] + matriksC[1][1]*matriksA[1][1];
        matriks1[2][0] = matriksC[2][0]*matriksA[0][0] + matriksC[2][1]*matriksA[1][0];
        matriks1[2][1] = matriksC[2][0]*matriksA[0][1] + matriksC[2][1]*matriksA[1][1];
        
        S1a.setText(String.valueOf(matriks1[0][0]));
        S1b.setText(String.valueOf(matriks1[0][1]));
        S1c.setText(String.valueOf(matriks1[1][0]));
        S1d.setText(String.valueOf(matriks1[1][1]));
        S1e.setText(String.valueOf(matriks1[2][0]));
        S1f.setText(String.valueOf(matriks1[2][1]));
        
        
        // Soal B
        int matriks2[][] = new int[2][2];
        int hasilB[][] = new int[2][2];
        for(int i=0; i<matriksA.length; i++){
            for(int j=0; j<matriksA[0].length; j++){
                hasilB[i][j] = matriksA[i][j] + matriksB[i][j];
            }
        }
        
        for(int i=0; i<Atr.length; i++){
            for(int j=0; j<Atr[0].length; j++){
                int x = 0;
                for(int k=0; k<Atr.length; k++){
                    x += Atr[i][k] * hasilB[k][j];
                }
                matriks2[i][j] = x;
            }
        }
        
        S2a.setText(String.valueOf(matriks2[0][0]));
        S2b.setText(String.valueOf(matriks2[0][1]));
        S2c.setText(String.valueOf(matriks2[1][0]));
        S2d.setText(String.valueOf(matriks2[1][1]));
        
        
        // Soal C
        
        int matriks3[][] = new int[3][2];
        int hasilC [][] = new int[3][2];
        
        matriks3[0][0] = matriksC[0][0]*matriksB[0][0] + matriksC[0][1]*matriksB[1][0];
        matriks3[0][1] = matriksC[0][0]*matriksB[0][1] + matriksC[0][1]*matriksB[1][1];
        matriks3[1][0] = matriksC[1][0]*matriksB[0][0] + matriksC[1][1]*matriksB[1][0];
        matriks3[1][1] = matriksC[1][0]*matriksB[0][1] + matriksC[1][1]*matriksB[1][1];
        matriks3[2][0] = matriksC[2][0]*matriksB[0][0] + matriksC[2][1]*matriksB[1][0];
        matriks3[2][1] = matriksC[2][0]*matriksB[0][1] + matriksC[2][1]*matriksB[1][1];
        
        // tranpose
        S3a.setText(String.valueOf(matriks3[0][0]));
        S3b.setText(String.valueOf(matriks3[1][0]));
        S3c.setText(String.valueOf(matriks3[2][0]));
        S3d.setText(String.valueOf(matriks3[0][1]));
        S3e.setText(String.valueOf(matriks3[1][1]));
        S3f.setText(String.valueOf(matriks3[2][1]));
        
        
        // Sodal D
        
        int hasil1[][] = new int[2][2];
        int hasil2[][] = new int[2][2];
        int hasil[][] = new int[2][2];
        
        // Perkalian At x B
        for(int i=0; i<Atr.length; i++){
            for(int j=0; j<Atr[0].length; j++){
                int hasilx = 0;
                for(int k=0; k<Atr.length; k++){
                    hasilx += Atr[i][k] * matriksB[k][j];
                }
                hasil1[i][j] = hasilx;
            }
        }
        
        // Perkalian B x At
        for(int i=0; i<matriksB.length; i++){
            for(int j=0; j<matriksB[0].length; j++){
                int hasily = 0;
                for(int k=0; k<matriksB.length; k++){
                    hasily += matriksB[i][k] * Atr[k][j];
                }
                hasil2[i][j] = hasily;
            }
        }
        
        // Pengurangan setelah perkalian
        for(int i=0; i<hasil2.length; i++){
            for(int j=0; j<hasil2[0].length; j++){
                hasil[i][j] = hasil2[i][j] - hasil1[i][j];
            }
        }
        
        S4a.setText(String.valueOf(hasil[0][0]));
        S4b.setText(String.valueOf(hasil[0][1]));
        S4c.setText(String.valueOf(hasil[1][0]));
        S4d.setText(String.valueOf(hasil[1][1]));
        
    }//GEN-LAST:event_HitungTaskActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int matriks[][] = new int[2][2];
        int tranpose[][] = new int[2][2];
        
        try{
            matriks[0][0] = Integer.parseInt(A1.getText());
            matriks[0][1] = Integer.parseInt(A2.getText());
            matriks[1][0] = Integer.parseInt(A3.getText());
            matriks[1][1] = Integer.parseInt(A4.getText());
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Yang anda masukkan salah atau kosong");
        }
        for(int i=0; i<matriks.length; i++){
                for(int j=0; j<matriks[0].length; j++){
                    tranpose[j][i] = matriks[i][j];
                }
        }
        A1.setText(String.valueOf(tranpose[0][0]));
        A2.setText(String.valueOf(tranpose[0][1]));
        A3.setText(String.valueOf(tranpose[1][0]));
        A4.setText(String.valueOf(tranpose[1][1]));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int matriks[][] = new int[2][2];
        int tranpose[][] = new int[2][2];
        
        try{
            matriks[0][0] = Integer.parseInt(B1.getText());
            matriks[0][1] = Integer.parseInt(B2.getText());
            matriks[1][0] = Integer.parseInt(B3.getText());
            matriks[1][1] = Integer.parseInt(B4.getText());
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Yang anda masukkan salah atau kosong");
        }
        for(int i=0; i<matriks.length; i++){
                for(int j=0; j<matriks[0].length; j++){
                    tranpose[j][i] = matriks[i][j];
                }
        }
        B1.setText(String.valueOf(tranpose[0][0]));
        B2.setText(String.valueOf(tranpose[0][1]));
        B3.setText(String.valueOf(tranpose[1][0]));
        B4.setText(String.valueOf(tranpose[1][1]));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int matriks[][] = new int[3][3];
        int tranpose[][] = new int[3][3];
        
        try{
            matriks[0][0] = Integer.parseInt(jA1.getText());
            matriks[0][1] = Integer.parseInt(jA2.getText());
            matriks[0][2] = Integer.parseInt(jA3.getText());
            matriks[1][0] = Integer.parseInt(jA4.getText());
            matriks[1][1] = Integer.parseInt(jA5.getText());
            matriks[1][2] = Integer.parseInt(jA6.getText());
            matriks[2][0] = Integer.parseInt(jA7.getText());
            matriks[2][1] = Integer.parseInt(jA8.getText());
            matriks[2][2] = Integer.parseInt(jA9.getText());
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Yang anda masukkan salah atau kosong");
        }
        for(int i=0; i<matriks.length; i++){
                for(int j=0; j<matriks[0].length; j++){
                    tranpose[j][i] = matriks[i][j];
                }
        }
        jA1.setText(String.valueOf(tranpose[0][0]));
        jA2.setText(String.valueOf(tranpose[0][1]));
        jA3.setText(String.valueOf(tranpose[0][2]));
        jA4.setText(String.valueOf(tranpose[1][0]));
        jA5.setText(String.valueOf(tranpose[1][1]));
        jA6.setText(String.valueOf(tranpose[1][2]));
        jA7.setText(String.valueOf(tranpose[2][0]));
        jA8.setText(String.valueOf(tranpose[2][1]));
        jA9.setText(String.valueOf(tranpose[2][2]));                                    
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int matriks[][] = new int[3][3];
        int tranpose[][] = new int[3][3];
        
        try{
            matriks[0][0] = Integer.parseInt(jB1.getText());
            matriks[0][1] = Integer.parseInt(jB2.getText());
            matriks[0][2] = Integer.parseInt(jB3.getText());
            matriks[1][0] = Integer.parseInt(jB4.getText());
            matriks[1][1] = Integer.parseInt(jB5.getText());
            matriks[1][2] = Integer.parseInt(jB6.getText());
            matriks[2][0] = Integer.parseInt(jB7.getText());
            matriks[2][1] = Integer.parseInt(jB8.getText());
            matriks[2][2] = Integer.parseInt(jB9.getText());
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Yang anda masukkan salah atau kosong");
        }
        for(int i=0; i<matriks.length; i++){
                for(int j=0; j<matriks[0].length; j++){
                    tranpose[j][i] = matriks[i][j];
                }
        }
        jB1.setText(String.valueOf(tranpose[0][0]));
        jB2.setText(String.valueOf(tranpose[0][1]));
        jB3.setText(String.valueOf(tranpose[0][2]));
        jB4.setText(String.valueOf(tranpose[1][0]));
        jB5.setText(String.valueOf(tranpose[1][1]));
        jB6.setText(String.valueOf(tranpose[1][2]));
        jB7.setText(String.valueOf(tranpose[2][0]));
        jB8.setText(String.valueOf(tranpose[2][1]));
        jB9.setText(String.valueOf(tranpose[2][2]));    
    }//GEN-LAST:event_jButton6ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aritmatika().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A1;
    private javax.swing.JTextField A11;
    private javax.swing.JTextField A12;
    private javax.swing.JTextField A2;
    private javax.swing.JTextField A21;
    private javax.swing.JTextField A22;
    private javax.swing.JTextField A3;
    private javax.swing.JTextField A4;
    private javax.swing.JTextField B1;
    private javax.swing.JTextField B11;
    private javax.swing.JTextField B12;
    private javax.swing.JTextField B2;
    private javax.swing.JTextField B21;
    private javax.swing.JTextField B22;
    private javax.swing.JTextField B3;
    private javax.swing.JTextField B4;
    private javax.swing.JTextField C11;
    private javax.swing.JTextField C12;
    private javax.swing.JTextField C21;
    private javax.swing.JTextField C22;
    private javax.swing.JTextField C31;
    private javax.swing.JTextField C32;
    private javax.swing.JTextField H1;
    private javax.swing.JTextField H2;
    private javax.swing.JTextField H3;
    private javax.swing.JTextField H4;
    private javax.swing.JButton HitungTask;
    private javax.swing.JComboBox<String> Operasi1;
    private javax.swing.JComboBox<String> Operasi2;
    private javax.swing.JButton Reset2;
    private javax.swing.JButton Reset3;
    private javax.swing.JButton ResetTask;
    private javax.swing.JTextField S1a;
    private javax.swing.JTextField S1b;
    private javax.swing.JTextField S1c;
    private javax.swing.JTextField S1d;
    private javax.swing.JTextField S1e;
    private javax.swing.JTextField S1f;
    private javax.swing.JTextField S2a;
    private javax.swing.JTextField S2b;
    private javax.swing.JTextField S2c;
    private javax.swing.JTextField S2d;
    private javax.swing.JTextField S3a;
    private javax.swing.JTextField S3b;
    private javax.swing.JTextField S3c;
    private javax.swing.JTextField S3d;
    private javax.swing.JTextField S3e;
    private javax.swing.JTextField S3f;
    private javax.swing.JTextField S4a;
    private javax.swing.JTextField S4b;
    private javax.swing.JTextField S4c;
    private javax.swing.JTextField S4d;
    private javax.swing.JTextField jA1;
    private javax.swing.JTextField jA2;
    private javax.swing.JTextField jA3;
    private javax.swing.JTextField jA4;
    private javax.swing.JTextField jA5;
    private javax.swing.JTextField jA6;
    private javax.swing.JTextField jA7;
    private javax.swing.JTextField jA8;
    private javax.swing.JTextField jA9;
    private javax.swing.JTextField jB1;
    private javax.swing.JTextField jB2;
    private javax.swing.JTextField jB3;
    private javax.swing.JTextField jB4;
    private javax.swing.JTextField jB5;
    private javax.swing.JTextField jB6;
    private javax.swing.JTextField jB7;
    private javax.swing.JTextField jB8;
    private javax.swing.JTextField jB9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JTextField jH1;
    private javax.swing.JTextField jH2;
    private javax.swing.JTextField jH3;
    private javax.swing.JTextField jH4;
    private javax.swing.JTextField jH5;
    private javax.swing.JTextField jH6;
    private javax.swing.JTextField jH7;
    private javax.swing.JTextField jH8;
    private javax.swing.JTextField jH9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
