/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kalkulator_matriks;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;
/**
 *
 * @author Asus x441
 */
public class InversMatriks extends javax.swing.JFrame {
    DecimalFormat df = new DecimalFormat("#.##");
    /**
     * Creates new form InversMatriks
     */
    public InversMatriks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        dua12 = new javax.swing.JTextField();
        dua21 = new javax.swing.JTextField();
        dua22 = new javax.swing.JTextField();
        dua11 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        hDua11 = new javax.swing.JTextField();
        hDua12 = new javax.swing.JTextField();
        hDua21 = new javax.swing.JTextField();
        hDua22 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        tiga12 = new javax.swing.JTextField();
        tiga11 = new javax.swing.JTextField();
        tiga13 = new javax.swing.JTextField();
        tiga23 = new javax.swing.JTextField();
        tiga22 = new javax.swing.JTextField();
        tiga21 = new javax.swing.JTextField();
        tiga33 = new javax.swing.JTextField();
        tiga32 = new javax.swing.JTextField();
        tiga31 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        hTiga11 = new javax.swing.JTextField();
        hTiga12 = new javax.swing.JTextField();
        hTiga13 = new javax.swing.JTextField();
        hTiga23 = new javax.swing.JTextField();
        hTiga22 = new javax.swing.JTextField();
        hTiga21 = new javax.swing.JTextField();
        hTiga31 = new javax.swing.JTextField();
        hTiga32 = new javax.swing.JTextField();
        hTiga33 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("INVERS MATRIKS");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(350, 30, 113, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("=");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(390, 190, 13, 25);

        jButton6.setBackground(new java.awt.Color(153, 204, 255));
        jButton6.setText("Kembali");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(30, 420, 99, 22);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Matriks"));
        jPanel8.setLayout(null);

        dua12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dua12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dua12ActionPerformed(evt);
            }
        });
        jPanel8.add(dua12);
        dua12.setBounds(69, 24, 50, 30);

        dua21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel8.add(dua21);
        dua21.setBounds(11, 60, 50, 30);

        dua22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel8.add(dua22);
        dua22.setBounds(69, 60, 50, 30);

        dua11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel8.add(dua11);
        dua11.setBounds(11, 24, 50, 30);

        jPanel1.add(jPanel8);
        jPanel8.setBounds(180, 150, 130, 110);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Hasil Invers"));
        jPanel7.setLayout(null);

        hDua11.setEditable(false);
        hDua11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(hDua11);
        hDua11.setBounds(11, 24, 50, 30);

        hDua12.setEditable(false);
        hDua12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(hDua12);
        hDua12.setBounds(69, 24, 50, 30);

        hDua21.setEditable(false);
        hDua21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(hDua21);
        hDua21.setBounds(11, 60, 50, 30);

        hDua22.setEditable(false);
        hDua22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(hDua22);
        hDua22.setBounds(69, 60, 50, 30);

        jPanel1.add(jPanel7);
        jPanel7.setBounds(480, 150, 130, 110);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setText("Ordo 2 x 2");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(370, 70, 60, 16);

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setText("HITUNG");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(310, 300, 170, 35);

        jButton8.setBackground(new java.awt.Color(255, 0, 0));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("RESET");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(310, 340, 170, 35);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Lorenza\\Matkul sem 3\\Aljabar Linear dan Matriks\\Tugas\\20230114_175711_0000.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 470);

        jTabbedPane1.addTab("2 x 2", jPanel1);

        jPanel2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("=");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(390, 190, 13, 25);

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setText("HITUNG");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(310, 300, 170, 35);

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("RESET");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(310, 340, 170, 35);

        jButton7.setBackground(new java.awt.Color(153, 204, 255));
        jButton7.setText("Kembali");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(30, 420, 99, 22);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Matriks"));
        jPanel3.setLayout(null);

        tiga12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(tiga12);
        tiga12.setBounds(67, 24, 50, 30);

        tiga11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(tiga11);
        tiga11.setBounds(11, 24, 50, 30);

        tiga13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(tiga13);
        tiga13.setBounds(123, 24, 50, 30);

        tiga23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(tiga23);
        tiga23.setBounds(123, 60, 50, 30);

        tiga22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(tiga22);
        tiga22.setBounds(67, 60, 50, 30);

        tiga21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(tiga21);
        tiga21.setBounds(11, 60, 50, 30);

        tiga33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(tiga33);
        tiga33.setBounds(123, 96, 50, 30);

        tiga32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(tiga32);
        tiga32.setBounds(67, 96, 50, 30);

        tiga31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(tiga31);
        tiga31.setBounds(11, 96, 50, 30);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(150, 140, 190, 140);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Hasil Invers"));
        jPanel4.setLayout(null);

        hTiga11.setEditable(false);
        hTiga11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(hTiga11);
        hTiga11.setBounds(11, 24, 50, 30);

        hTiga12.setEditable(false);
        hTiga12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(hTiga12);
        hTiga12.setBounds(67, 24, 50, 30);

        hTiga13.setEditable(false);
        hTiga13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(hTiga13);
        hTiga13.setBounds(123, 24, 50, 30);

        hTiga23.setEditable(false);
        hTiga23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(hTiga23);
        hTiga23.setBounds(123, 60, 50, 30);

        hTiga22.setEditable(false);
        hTiga22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(hTiga22);
        hTiga22.setBounds(67, 60, 50, 30);

        hTiga21.setEditable(false);
        hTiga21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(hTiga21);
        hTiga21.setBounds(11, 60, 50, 30);

        hTiga31.setEditable(false);
        hTiga31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(hTiga31);
        hTiga31.setBounds(11, 96, 50, 30);

        hTiga32.setEditable(false);
        hTiga32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(hTiga32);
        hTiga32.setBounds(67, 96, 50, 30);

        hTiga33.setEditable(false);
        hTiga33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(hTiga33);
        hTiga33.setBounds(123, 96, 50, 30);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(460, 140, 190, 140);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel9.setText("Ordo 3 x 3");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(370, 70, 60, 16);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("INVERS MATRIKS");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(350, 30, 113, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Lorenza\\Matkul sem 3\\Aljabar Linear dan Matriks\\Tugas\\20230114_175711_0000.png")); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 470);

        jTabbedPane1.addTab("3 x 3", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void dua12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dua12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dua12ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int matriks2x2[][] = new int[2][2];
        try{
            matriks2x2[0][0] = Integer.parseInt(dua11.getText());
            matriks2x2[0][1] = Integer.parseInt(dua12.getText());
            matriks2x2[1][0] = Integer.parseInt(dua21.getText());
            matriks2x2[1][1] = Integer.parseInt(dua22.getText());
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Yang anda masukkan salah atau kosong");
        }

        int hasil2x2[][] = new int[2][2];

        // Determinan matriks 2x2
        int det;
        det = matriks2x2[0][0]*matriks2x2[1][1] - matriks2x2[0][1]*matriks2x2[1][0];

        // Menukar posisi matriks a dan d dan kali -1 untuk b dan c
        int tukar;
        tukar = matriks2x2[0][0];
        matriks2x2[0][0] = matriks2x2[1][1];
        matriks2x2[1][1] = tukar;
        matriks2x2[0][1] *= -1;
        matriks2x2[1][0] *= -1;

        // Adjoin
        hasil2x2[0][0] = matriks2x2[0][0];
        hasil2x2[0][1] = matriks2x2[0][1];
        hasil2x2[1][0] = matriks2x2[1][0];
        hasil2x2[1][1] = matriks2x2[1][1];

        // Convert Int to Double
        double dtr = det;
        double hasil[][] = new double [2][2];
        hasil[0][0] = hasil2x2[0][0] / dtr;
        hasil[0][1] = hasil2x2[0][1] / dtr;
        hasil[1][0] = hasil2x2[1][0] / dtr;
        hasil[1][1] = hasil2x2[1][1] / dtr;

        // Output Invers
        hDua11.setText(String.valueOf(df.format(hasil[0][0])));
        hDua12.setText(String.valueOf(df.format(hasil[0][1])));
        hDua21.setText(String.valueOf(df.format(hasil[1][0])));
        hDua22.setText(String.valueOf(df.format(hasil[1][1])));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        dua11.setText("");
        dua12.setText("");
        dua21.setText("");
        dua22.setText("");
        hDua11.setText("");
        hDua12.setText("");
        hDua21.setText("");
        hDua22.setText("");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int matriks3x3[][] = new int[3][3];
        try{
            matriks3x3[0][0] = Integer.parseInt(tiga11.getText());
            matriks3x3[0][1] = Integer.parseInt(tiga12.getText());
            matriks3x3[0][2] = Integer.parseInt(tiga13.getText());
            matriks3x3[1][0] = Integer.parseInt(tiga21.getText());
            matriks3x3[1][1] = Integer.parseInt(tiga22.getText());
            matriks3x3[1][2] = Integer.parseInt(tiga23.getText());
            matriks3x3[2][0] = Integer.parseInt(tiga31.getText());
            matriks3x3[2][1] = Integer.parseInt(tiga32.getText());
            matriks3x3[2][2] = Integer.parseInt(tiga33.getText());
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Yang anda masukkan salah atau kosong");
        }

        double hasil3x3[][] = new double[3][3];

        // Determinan matriks 3x3
        int silang1, silang2, det;
        silang1 = matriks3x3[0][0]*matriks3x3[1][1]*matriks3x3[2][2] + matriks3x3[0][1]*matriks3x3[1][2]*matriks3x3[2][0] + matriks3x3[0][2]*matriks3x3[1][0]*matriks3x3[2][1];
        silang2 = matriks3x3[2][0]*matriks3x3[1][1]*matriks3x3[0][2] + matriks3x3[2][1]*matriks3x3[1][2]*matriks3x3[0][0] + matriks3x3[2][2]*matriks3x3[1][0]*matriks3x3[0][1];
        det = silang1 - silang2;

        // Minor
        hasil3x3[0][0] = matriks3x3[1][1]*matriks3x3[2][2] - matriks3x3[1][2]*matriks3x3[2][1];
        hasil3x3[0][1] = matriks3x3[1][0]*matriks3x3[2][2] - matriks3x3[1][2]*matriks3x3[2][0];
        hasil3x3[0][2] = matriks3x3[1][0]*matriks3x3[2][1] - matriks3x3[1][1]*matriks3x3[2][0];
        hasil3x3[1][0] = matriks3x3[0][1]*matriks3x3[2][2] - matriks3x3[0][2]*matriks3x3[2][1];
        hasil3x3[1][1] = matriks3x3[0][0]*matriks3x3[2][2] - matriks3x3[0][2]*matriks3x3[2][0];
        hasil3x3[1][2] = matriks3x3[0][0]*matriks3x3[2][1] - matriks3x3[0][1]*matriks3x3[2][0];
        hasil3x3[2][0] = matriks3x3[0][1]*matriks3x3[1][2] - matriks3x3[0][2]*matriks3x3[1][1];
        hasil3x3[2][1] = matriks3x3[0][0]*matriks3x3[1][2] - matriks3x3[0][2]*matriks3x3[1][0];
        hasil3x3[2][2] = matriks3x3[0][0]*matriks3x3[1][1] - matriks3x3[0][1]*matriks3x3[1][0];

        // Kofaktor
        hasil3x3[0][0] *= 1;
        hasil3x3[0][1] *= -1;
        hasil3x3[0][2] *= 1;
        hasil3x3[1][0] *= -1;
        hasil3x3[1][1] *= 1;
        hasil3x3[1][2] *= -1;
        hasil3x3[2][0] *= 1;
        hasil3x3[2][1] *= -1;
        hasil3x3[2][2] *= 1;

        // Adjoin & convert int to double
        double dtr = det;
        double hasil[][] = new double [3][3];
        hasil[0][0] = hasil3x3[0][0] / dtr;
        hasil[0][1] = hasil3x3[0][1] / dtr;
        hasil[0][2] = hasil3x3[0][2] / dtr;
        hasil[1][0] = hasil3x3[1][0] / dtr;
        hasil[1][1] = hasil3x3[1][1] / dtr;
        hasil[1][2] = hasil3x3[1][2] / dtr;
        hasil[2][0] = hasil3x3[2][0] / dtr;
        hasil[2][1] = hasil3x3[2][1] / dtr;
        hasil[2][2] = hasil3x3[2][2] / dtr;

        hTiga11.setText(String.valueOf(df.format(hasil[0][0])));
        hTiga12.setText(String.valueOf(df.format(hasil[0][1])));
        hTiga13.setText(String.valueOf(df.format(hasil[0][2])));
        hTiga21.setText(String.valueOf(df.format(hasil[1][0])));
        hTiga22.setText(String.valueOf(df.format(hasil[1][1])));
        hTiga23.setText(String.valueOf(df.format(hasil[1][2])));
        hTiga31.setText(String.valueOf(df.format(hasil[2][0])));
        hTiga32.setText(String.valueOf(df.format(hasil[2][1])));
        hTiga33.setText(String.valueOf(df.format(hasil[2][2])));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        tiga11.setText("");
        tiga12.setText("");
        tiga13.setText("");
        tiga21.setText("");
        tiga22.setText("");
        tiga23.setText("");
        tiga31.setText("");
        tiga32.setText("");
        tiga33.setText("");
        hTiga11.setText("");
        hTiga12.setText("");
        hTiga13.setText("");
        hTiga21.setText("");
        hTiga22.setText("");
        hTiga23.setText("");
        hTiga31.setText("");
        hTiga32.setText("");
        hTiga33.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InversMatriks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InversMatriks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InversMatriks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InversMatriks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InversMatriks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dua11;
    private javax.swing.JTextField dua12;
    private javax.swing.JTextField dua21;
    private javax.swing.JTextField dua22;
    private javax.swing.JTextField hDua11;
    private javax.swing.JTextField hDua12;
    private javax.swing.JTextField hDua21;
    private javax.swing.JTextField hDua22;
    private javax.swing.JTextField hTiga11;
    private javax.swing.JTextField hTiga12;
    private javax.swing.JTextField hTiga13;
    private javax.swing.JTextField hTiga21;
    private javax.swing.JTextField hTiga22;
    private javax.swing.JTextField hTiga23;
    private javax.swing.JTextField hTiga31;
    private javax.swing.JTextField hTiga32;
    private javax.swing.JTextField hTiga33;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField tiga11;
    private javax.swing.JTextField tiga12;
    private javax.swing.JTextField tiga13;
    private javax.swing.JTextField tiga21;
    private javax.swing.JTextField tiga22;
    private javax.swing.JTextField tiga23;
    private javax.swing.JTextField tiga31;
    private javax.swing.JTextField tiga32;
    private javax.swing.JTextField tiga33;
    // End of variables declaration//GEN-END:variables
}
