package kalkulator_matriks;


import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author digit
 */
public class SplMatriks extends javax.swing.JFrame {
    DecimalFormat df = new DecimalFormat("#.##");
    /**
     * Creates new form SplMatriks
     */
    public SplMatriks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        x3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        y3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        z3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        h3 = new javax.swing.JTextField();
        h2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        z2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        y2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        x2 = new javax.swing.JTextField();
        h1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        z1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        y1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        x1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        D = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        Dx = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Dy = new javax.swing.JTextField();
        Dz = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        x = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        y = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        z = new javax.swing.JTextField();
        d3 = new javax.swing.JLabel();
        d1 = new javax.swing.JLabel();
        d2 = new javax.swing.JLabel();
        d4 = new javax.swing.JLabel();
        d5 = new javax.swing.JLabel();
        d6 = new javax.swing.JLabel();
        d7 = new javax.swing.JLabel();
        d9 = new javax.swing.JLabel();
        d8 = new javax.swing.JLabel();
        jSeparator24 = new javax.swing.JSeparator();
        dx1 = new javax.swing.JLabel();
        dx2 = new javax.swing.JLabel();
        dx3 = new javax.swing.JLabel();
        dx9 = new javax.swing.JLabel();
        dx5 = new javax.swing.JLabel();
        dx4 = new javax.swing.JLabel();
        dx7 = new javax.swing.JLabel();
        dx8 = new javax.swing.JLabel();
        dx6 = new javax.swing.JLabel();
        jSeparator25 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator26 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator27 = new javax.swing.JSeparator();
        d19 = new javax.swing.JLabel();
        dz8 = new javax.swing.JLabel();
        dz1 = new javax.swing.JLabel();
        dy9 = new javax.swing.JLabel();
        dy3 = new javax.swing.JLabel();
        jSeparator28 = new javax.swing.JSeparator();
        dz3 = new javax.swing.JLabel();
        dy2 = new javax.swing.JLabel();
        jSeparator20 = new javax.swing.JSeparator();
        dz9 = new javax.swing.JLabel();
        dz4 = new javax.swing.JLabel();
        dy7 = new javax.swing.JLabel();
        dy6 = new javax.swing.JLabel();
        dy5 = new javax.swing.JLabel();
        jSeparator21 = new javax.swing.JSeparator();
        dy4 = new javax.swing.JLabel();
        dz7 = new javax.swing.JLabel();
        dy1 = new javax.swing.JLabel();
        dz2 = new javax.swing.JLabel();
        jSeparator29 = new javax.swing.JSeparator();
        dy8 = new javax.swing.JLabel();
        dz5 = new javax.swing.JLabel();
        dz6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SPL Aturan Cramer");

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("SPL");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(390, 0, 40, 25);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel3.setText("(Menggunakan Aturan Cramer)");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(320, 20, 168, 16);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Input 3 Persamaan"));
        jPanel2.setLayout(null);

        x3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x3ActionPerformed(evt);
            }
        });
        jPanel2.add(x3);
        x3.setBounds(20, 110, 45, 22);

        jLabel10.setText("+");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(70, 110, 8, 16);

        y3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        y3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y3ActionPerformed(evt);
            }
        });
        jPanel2.add(y3);
        y3.setBounds(80, 110, 45, 22);

        jLabel11.setText("+");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(130, 110, 8, 16);

        z3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        z3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                z3ActionPerformed(evt);
            }
        });
        jPanel2.add(z3);
        z3.setBounds(140, 110, 45, 22);

        jLabel12.setText("=");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(190, 110, 8, 16);

        h3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        h3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h3ActionPerformed(evt);
            }
        });
        jPanel2.add(h3);
        h3.setBounds(200, 110, 45, 22);

        h2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        h2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h2ActionPerformed(evt);
            }
        });
        jPanel2.add(h2);
        h2.setBounds(200, 80, 45, 22);

        jLabel21.setText("=");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(190, 80, 8, 16);

        z2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        z2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                z2ActionPerformed(evt);
            }
        });
        jPanel2.add(z2);
        z2.setBounds(140, 80, 45, 22);

        jLabel22.setText("+");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(130, 80, 8, 16);

        y2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        y2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y2ActionPerformed(evt);
            }
        });
        jPanel2.add(y2);
        y2.setBounds(80, 80, 45, 22);

        jLabel23.setText("+");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(70, 80, 8, 16);

        x2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x2ActionPerformed(evt);
            }
        });
        jPanel2.add(x2);
        x2.setBounds(20, 80, 45, 22);

        h1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        h1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h1ActionPerformed(evt);
            }
        });
        jPanel2.add(h1);
        h1.setBounds(200, 50, 45, 22);

        jLabel24.setText("=");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(190, 50, 8, 16);

        z1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        z1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                z1ActionPerformed(evt);
            }
        });
        jPanel2.add(z1);
        z1.setBounds(140, 50, 45, 22);

        jLabel25.setText("+");
        jPanel2.add(jLabel25);
        jLabel25.setBounds(130, 50, 8, 16);

        y1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        y1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y1ActionPerformed(evt);
            }
        });
        jPanel2.add(y1);
        y1.setBounds(80, 50, 45, 22);

        jLabel26.setText("+");
        jPanel2.add(jLabel26);
        jLabel26.setBounds(70, 50, 8, 16);

        x1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x1ActionPerformed(evt);
            }
        });
        jPanel2.add(x1);
        x1.setBounds(20, 50, 45, 22);

        jLabel4.setFont(new java.awt.Font("Calisto MT", 3, 14)); // NOI18N
        jLabel4.setText("z");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(160, 20, 10, 17);

        jLabel5.setFont(new java.awt.Font("Calisto MT", 3, 14)); // NOI18N
        jLabel5.setText("x");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(40, 20, 10, 17);

        jLabel6.setFont(new java.awt.Font("Calisto MT", 3, 14)); // NOI18N
        jLabel6.setText("y");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(100, 20, 10, 17);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(180, 60, 260, 140);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setText("HITUNG");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(490, 90, 140, 50);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(490, 150, 140, 22);

        jButton5.setBackground(new java.awt.Color(153, 204, 255));
        jButton5.setText("Kembali");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(40, 460, 100, 22);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hasil", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel3.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel13.setText("=");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(240, 60, 10, 16);

        jSeparator16.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator16.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator16);
        jSeparator16.setBounds(70, 20, 3, 90);

        jSeparator17.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator17.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator17);
        jSeparator17.setBounds(230, 20, 10, 90);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel14.setText("det Dx =");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(10, 170, 50, 16);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel15.setText("det D =");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(20, 60, 40, 16);

        D.setEditable(false);
        D.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        D.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel3.add(D);
        D.setBounds(260, 50, 40, 40);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel16.setText("=");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(240, 170, 10, 16);

        Dx.setEditable(false);
        Dx.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Dx.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel3.add(Dx);
        Dx.setBounds(260, 160, 40, 40);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel17.setText("det Dy =");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(320, 60, 50, 16);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel18.setText("=");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(550, 60, 10, 16);

        Dy.setEditable(false);
        Dy.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Dy.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel3.add(Dy);
        Dy.setBounds(570, 50, 40, 40);

        Dz.setEditable(false);
        Dz.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Dz.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel3.add(Dz);
        Dz.setBounds(570, 160, 40, 40);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel19.setText("=");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(550, 170, 10, 16);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel20.setText("det Dz =");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(320, 170, 50, 16);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "x", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calisto MT", 3, 18))); // NOI18N
        jPanel5.setLayout(null);

        x.setEditable(false);
        x.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        x.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xActionPerformed(evt);
            }
        });
        jPanel5.add(x);
        x.setBounds(11, 24, 64, 26);

        jPanel3.add(jPanel5);
        jPanel5.setBounds(640, 20, 90, 60);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "y", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calisto MT", 3, 18))); // NOI18N
        jPanel6.setLayout(null);

        y.setEditable(false);
        y.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        y.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel6.add(y);
        y.setBounds(11, 24, 64, 26);

        jPanel3.add(jPanel6);
        jPanel6.setBounds(640, 90, 90, 60);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "z", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calisto MT", 3, 18))); // NOI18N
        jPanel7.setLayout(null);

        z.setEditable(false);
        z.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        z.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(z);
        z.setBounds(11, 24, 64, 26);

        jPanel3.add(jPanel7);
        jPanel7.setBounds(640, 160, 90, 60);

        d3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(d3);
        d3.setBounds(180, 20, 40, 30);

        d1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(d1);
        d1.setBounds(80, 20, 40, 30);

        d2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(d2);
        d2.setBounds(130, 20, 40, 30);

        d4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(d4);
        d4.setBounds(80, 50, 40, 30);

        d5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(d5);
        d5.setBounds(130, 50, 40, 30);

        d6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(d6);
        d6.setBounds(180, 50, 40, 30);

        d7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(d7);
        d7.setBounds(80, 80, 40, 30);

        d9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(d9);
        d9.setBounds(180, 80, 40, 30);

        d8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(d8);
        d8.setBounds(130, 80, 40, 30);

        jSeparator24.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator24.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator24);
        jSeparator24.setBounds(70, 130, 3, 90);

        dx1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(dx1);
        dx1.setBounds(80, 130, 40, 30);

        dx2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(dx2);
        dx2.setBounds(130, 130, 40, 30);

        dx3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(dx3);
        dx3.setBounds(180, 130, 40, 30);

        dx9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(dx9);
        dx9.setBounds(180, 190, 40, 30);

        dx5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(dx5);
        dx5.setBounds(130, 160, 40, 30);

        dx4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(dx4);
        dx4.setBounds(80, 160, 40, 30);

        dx7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(dx7);
        dx7.setBounds(80, 190, 40, 30);

        dx8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(dx8);
        dx8.setBounds(130, 190, 40, 30);

        dx6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(dx6);
        dx6.setBounds(180, 160, 40, 30);

        jSeparator25.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator25.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator25);
        jSeparator25.setBounds(230, 130, 10, 90);

        jSeparator18.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator18.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator18);
        jSeparator18.setBounds(70, 20, 3, 90);

        jSeparator26.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator26.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator26);
        jSeparator26.setBounds(70, 130, 3, 90);

        jSeparator19.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator19.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator19);
        jSeparator19.setBounds(230, 20, 10, 90);

        jSeparator27.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator27.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator27);
        jSeparator27.setBounds(230, 130, 10, 90);

        d19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(d19);
        d19.setBounds(180, 20, 40, 30);

        dz8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(dz8);
        dz8.setBounds(440, 190, 40, 30);

        dz1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(dz1);
        dz1.setBounds(390, 130, 40, 30);

        dy9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(dy9);
        dy9.setBounds(490, 80, 40, 30);

        dy3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(dy3);
        dy3.setBounds(490, 20, 40, 30);

        jSeparator28.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator28.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator28);
        jSeparator28.setBounds(380, 130, 3, 90);

        dz3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(dz3);
        dz3.setBounds(490, 130, 40, 30);

        dy2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(dy2);
        dy2.setBounds(440, 20, 40, 30);

        jSeparator20.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator20.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator20);
        jSeparator20.setBounds(540, 20, 10, 90);

        dz9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(dz9);
        dz9.setBounds(490, 190, 40, 30);

        dz4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(dz4);
        dz4.setBounds(390, 160, 40, 30);

        dy7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(dy7);
        dy7.setBounds(390, 80, 40, 30);

        dy6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(dy6);
        dy6.setBounds(490, 50, 40, 30);

        dy5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(dy5);
        dy5.setBounds(440, 50, 40, 30);

        jSeparator21.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator21.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator21);
        jSeparator21.setBounds(380, 20, 3, 90);

        dy4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(dy4);
        dy4.setBounds(390, 50, 40, 30);

        dz7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(dz7);
        dz7.setBounds(390, 190, 40, 30);

        dy1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(dy1);
        dy1.setBounds(390, 20, 40, 30);

        dz2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(dz2);
        dz2.setBounds(440, 130, 40, 30);

        jSeparator29.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator29.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator29);
        jSeparator29.setBounds(540, 130, 10, 90);

        dy8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(dy8);
        dy8.setBounds(440, 80, 40, 30);

        dz5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(dz5);
        dz5.setBounds(440, 160, 40, 30);

        dz6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(dz6);
        dz6.setBounds(490, 160, 40, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(30, 210, 750, 240);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Lorenza\\Matkul sem 3\\Aljabar Linear dan Matriks\\Tugas\\20230114_175711_0000.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x3ActionPerformed

    private void y3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y3ActionPerformed

    private void z3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_z3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_z3ActionPerformed

    private void h3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_h3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xActionPerformed

    private void h2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_h2ActionPerformed

    private void z2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_z2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_z2ActionPerformed

    private void y2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y2ActionPerformed

    private void x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x2ActionPerformed

    private void h1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_h1ActionPerformed

    private void z1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_z1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_z1ActionPerformed

    private void y1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y1ActionPerformed

    private void x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int spl[][] = new int[3][4];
        try{
            spl[0][0] = Integer.parseInt(x1.getText());
            spl[0][1] = Integer.parseInt(y1.getText());
            spl[0][2] = Integer.parseInt(z1.getText());
            spl[0][3] = Integer.parseInt(h1.getText());
            spl[1][0] = Integer.parseInt(x2.getText());
            spl[1][1] = Integer.parseInt(y2.getText());
            spl[1][2] = Integer.parseInt(z2.getText());
            spl[1][3] = Integer.parseInt(h2.getText());
            spl[2][0] = Integer.parseInt(x3.getText());
            spl[2][1] = Integer.parseInt(y3.getText());
            spl[2][2] = Integer.parseInt(z3.getText());
            spl[2][3] = Integer.parseInt(h3.getText());
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Yang anda masukkan salah atau kosong");
        }
        
        int matD[][] = new int [3][3];
        int matDx[][] = new int [3][3];
        int matDy[][] = new int [3][3];
        int matDz[][] = new int [3][3];
        int detD, detDx, detDy, detDz;
        
        // Hasil Determinan D
        matD[0][0] = spl[0][0];
        matD[0][1] = spl[0][1];
        matD[0][2] = spl[0][2];
        matD[1][0] = spl[1][0];
        matD[1][1] = spl[1][1];
        matD[1][2] = spl[1][2];
        matD[2][0] = spl[2][0];
        matD[2][1] = spl[2][1];
        matD[2][2] = spl[2][2];
        
        detD = (matD[0][0]*matD[1][1]*matD[2][2] + matD[0][1]*matD[1][2]*matD[2][0] + matD[0][2]*matD[1][0]*matD[2][1]) - (matD[2][0]*matD[1][1]*matD[0][2] + matD[2][1]*matD[1][2]*matD[0][0] + matD[2][2]*matD[1][0]*matD[0][1]);
        
        d1.setText(String.valueOf(matD[0][0]));
        d2.setText(String.valueOf(matD[0][1]));
        d3.setText(String.valueOf(matD[0][2]));
        d4.setText(String.valueOf(matD[1][0]));
        d5.setText(String.valueOf(matD[1][1]));
        d6.setText(String.valueOf(matD[1][2]));
        d7.setText(String.valueOf(matD[2][0]));
        d8.setText(String.valueOf(matD[2][1]));
        d9.setText(String.valueOf(matD[2][2]));
        D.setText(String.valueOf(detD));
        
        // Hasil Determinan Dx
        matDx[0][0] = spl[0][3];
        matDx[0][1] = spl[0][1];
        matDx[0][2] = spl[0][2];
        matDx[1][0] = spl[1][3];
        matDx[1][1] = spl[1][1];
        matDx[1][2] = spl[1][2];
        matDx[2][0] = spl[2][3];
        matDx[2][1] = spl[2][1];
        matDx[2][2] = spl[2][2];
        
        detDx = (matDx[0][0]*matDx[1][1]*matDx[2][2] + matDx[0][1]*matDx[1][2]*matDx[2][0] + matDx[0][2]*matDx[1][0]*matDx[2][1]) - (matDx[2][0]*matDx[1][1]*matDx[0][2] + matDx[2][1]*matDx[1][2]*matDx[0][0] + matDx[2][2]*matDx[1][0]*matDx[0][1]);
        
        dx1.setText(String.valueOf(matDx[0][0]));
        dx2.setText(String.valueOf(matDx[0][1]));
        dx3.setText(String.valueOf(matDx[0][2]));
        dx4.setText(String.valueOf(matDx[1][0]));
        dx5.setText(String.valueOf(matDx[1][1]));
        dx6.setText(String.valueOf(matDx[1][2]));
        dx7.setText(String.valueOf(matDx[2][0]));
        dx8.setText(String.valueOf(matDx[2][1]));
        dx9.setText(String.valueOf(matDx[2][2]));
        Dx.setText(String.valueOf(detDx));
        
        // Hasil Determinan Dy
        matDy[0][0] = spl[0][0];
        matDy[0][1] = spl[0][3];
        matDy[0][2] = spl[0][2];
        matDy[1][0] = spl[1][0];
        matDy[1][1] = spl[1][3];
        matDy[1][2] = spl[1][2];
        matDy[2][0] = spl[2][0];
        matDy[2][1] = spl[2][3];
        matDy[2][2] = spl[2][2];
        
        detDy = (matDy[0][0]*matDy[1][1]*matDy[2][2] + matDy[0][1]*matDy[1][2]*matDy[2][0] + matDy[0][2]*matDy[1][0]*matDy[2][1]) - (matDy[2][0]*matDy[1][1]*matDy[0][2] + matDy[2][1]*matDy[1][2]*matDy[0][0] + matDy[2][2]*matDy[1][0]*matDy[0][1]);
        
        dy1.setText(String.valueOf(matDy[0][0]));
        dy2.setText(String.valueOf(matDy[0][1]));
        dy3.setText(String.valueOf(matDy[0][2]));
        dy4.setText(String.valueOf(matDy[1][0]));
        dy5.setText(String.valueOf(matDy[1][1]));
        dy6.setText(String.valueOf(matDy[1][2]));
        dy7.setText(String.valueOf(matDy[2][0]));
        dy8.setText(String.valueOf(matDy[2][1]));
        dy9.setText(String.valueOf(matDy[2][2]));
        Dy.setText(String.valueOf(detDy));
        
         // Hasil Determinan Dz
        matDz[0][0] = spl[0][0];
        matDz[0][1] = spl[0][1];
        matDz[0][2] = spl[0][3];
        matDz[1][0] = spl[1][0];
        matDz[1][1] = spl[1][1];
        matDz[1][2] = spl[1][3];
        matDz[2][0] = spl[2][0];
        matDz[2][1] = spl[2][1];
        matDz[2][2] = spl[2][3];
        
        detDz = (matDz[0][0]*matDz[1][1]*matDz[2][2] + matDz[0][1]*matDz[1][2]*matDz[2][0] + matDz[0][2]*matDz[1][0]*matDz[2][1]) - (matDz[2][0]*matDz[1][1]*matDz[0][2] + matDz[2][1]*matDz[1][2]*matDz[0][0] + matDz[2][2]*matDz[1][0]*matDz[0][1]);
        
        dz1.setText(String.valueOf(matDz[0][0]));
        dz2.setText(String.valueOf(matDz[0][1]));
        dz3.setText(String.valueOf(matDz[0][2]));
        dz4.setText(String.valueOf(matDz[1][0]));
        dz5.setText(String.valueOf(matDz[1][1]));
        dz6.setText(String.valueOf(matDz[1][2]));
        dz7.setText(String.valueOf(matDz[2][0]));
        dz8.setText(String.valueOf(matDz[2][1]));
        dz9.setText(String.valueOf(matDz[2][2]));
        Dz.setText(String.valueOf(detDz));
        
        // Convert Int to Double
        double dtrD, dtrX, dtrY, dtrZ;
        dtrD = detD;
        dtrX = detDx;
        dtrY = detDy;
        dtrZ = detDz;
        double hx, hy, hz;
        
        hx = dtrX / dtrD;
        hy = dtrY / dtrD;
        hz = dtrZ / dtrD;
        
        x.setText(String.valueOf(df.format(hx)));
        y.setText(String.valueOf(df.format(hy)));
        z.setText(String.valueOf(df.format(hz)));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        x1.setText("");
        x2.setText("");
        x3.setText("");
        y1.setText("");
        y2.setText("");
        y3.setText("");
        z1.setText("");
        z2.setText("");
        z3.setText("");
        h1.setText("");
        h2.setText("");
        h3.setText("");
        d1.setText("");
        d2.setText("");
        d3.setText("");
        d4.setText("");
        d5.setText("");
        d6.setText("");
        d7.setText("");
        d8.setText("");
        d9.setText("");
        dx1.setText("");
        dx2.setText("");
        dx3.setText("");
        dx4.setText("");
        dx5.setText("");
        dx6.setText("");
        dx7.setText("");
        dx8.setText("");
        dx9.setText("");
        dy1.setText("");
        dy2.setText("");
        dy3.setText("");
        dy4.setText("");
        dy5.setText("");
        dy6.setText("");
        dy7.setText("");
        dy8.setText("");
        dy9.setText("");
        dz1.setText("");
        dz2.setText("");
        dz3.setText("");
        dz4.setText("");
        dz5.setText("");
        dz6.setText("");
        dz7.setText("");
        dz8.setText("");
        dz9.setText("");
        D.setText("");
        Dx.setText("");
        Dy.setText("");
        Dy.setText("");
        x.setText("");
        y.setText("");
        z.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplMatriks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplMatriks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplMatriks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplMatriks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplMatriks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField D;
    private javax.swing.JTextField Dx;
    private javax.swing.JTextField Dy;
    private javax.swing.JTextField Dz;
    private javax.swing.JLabel d1;
    private javax.swing.JLabel d19;
    private javax.swing.JLabel d2;
    private javax.swing.JLabel d3;
    private javax.swing.JLabel d4;
    private javax.swing.JLabel d5;
    private javax.swing.JLabel d6;
    private javax.swing.JLabel d7;
    private javax.swing.JLabel d8;
    private javax.swing.JLabel d9;
    private javax.swing.JLabel dx1;
    private javax.swing.JLabel dx2;
    private javax.swing.JLabel dx3;
    private javax.swing.JLabel dx4;
    private javax.swing.JLabel dx5;
    private javax.swing.JLabel dx6;
    private javax.swing.JLabel dx7;
    private javax.swing.JLabel dx8;
    private javax.swing.JLabel dx9;
    private javax.swing.JLabel dy1;
    private javax.swing.JLabel dy2;
    private javax.swing.JLabel dy3;
    private javax.swing.JLabel dy4;
    private javax.swing.JLabel dy5;
    private javax.swing.JLabel dy6;
    private javax.swing.JLabel dy7;
    private javax.swing.JLabel dy8;
    private javax.swing.JLabel dy9;
    private javax.swing.JLabel dz1;
    private javax.swing.JLabel dz2;
    private javax.swing.JLabel dz3;
    private javax.swing.JLabel dz4;
    private javax.swing.JLabel dz5;
    private javax.swing.JLabel dz6;
    private javax.swing.JLabel dz7;
    private javax.swing.JLabel dz8;
    private javax.swing.JLabel dz9;
    private javax.swing.JTextField h1;
    private javax.swing.JTextField h2;
    private javax.swing.JTextField h3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JTextField x;
    private javax.swing.JTextField x1;
    private javax.swing.JTextField x2;
    private javax.swing.JTextField x3;
    private javax.swing.JTextField y;
    private javax.swing.JTextField y1;
    private javax.swing.JTextField y2;
    private javax.swing.JTextField y3;
    private javax.swing.JTextField z;
    private javax.swing.JTextField z1;
    private javax.swing.JTextField z2;
    private javax.swing.JTextField z3;
    // End of variables declaration//GEN-END:variables
}
